site_name: DaSCH Software Documentation

nav:
    - User Guide:
      - Introduction: user-guide/index.md
      - Project Management: user-guide/project.md
      - Data Management: user-guide/data.md
      # - Publication: user-guide/publication.md
    - Developers:
      - Documentation: developers/index.md
      - Getting started: developers/getting-started.md
      - API Reference: developers/api-reference.md
      - Contribution: developers/contribution.md
    - Community:
      - Discuss Forum: community/discuss.md
      - FAQ: community/faq.md
      - Product Updates: community/product-updates.md
      - About us: community/about-us.md


theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  feature:
    tabs: true
extra_css:
  - 'assets/style/theme.css'